# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/whitelist-source-range: 80.72.28.185
#     cert-manager.io/issuer: gitlab-issuer
#     kubernetes.io/ingress.class: nginx
#   name: ingress-nginxservice-a
#   namespace: monitoring
# spec:
#   rules:
#   - host: localhost  # Укажите свой домен или IP-адрес
#     http:
#       paths:
#       - backend:
#           service:
#             name: nginxservice  # Укажите имя сервиса Grafana
#             port:
#               number: 80  # Укажите порт сервиса Grafana
#         path: /
#         pathType: Prefix   
#   tls: 
#   - hosts: 
#     - localhost # Укажите свой домен или IP-адрес
#     secretName: grafanassl

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myhelmapp-grafana-ingress
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 80.72.28.185
    cert-manager.io/issuer: gitlab-issuer
    kubernetes.io/ingress.class: nginx
  namespace: monitoring
spec:
  rules:
    - host: localhost
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: myhelmapp
          #       port:
          #         number: 80

          # - path: /myhelmapp-dev
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: myhelmapp
          #       port:
          #         number: 80

          # - path: /myhelmapp-prod
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: myhelmapp
          #       port:
          #         number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80